Dev
dimabalony/Todo-list-lab1 pull request #1
Opened 2020-04-23 10:28 UTC by dimabalony

2020-04-25 14:00 UTC, DmitryGolubko requested changes
В целом ок, но похоже что нашел какой то баг. Таска Done, а даты нет. 
![image](https://user-images.githubusercontent.com/22429308/80281628-2f8c2c80-8715-11ea-86a8-54e829f13122.png) Надо бы поправить. Это одно.
Второе, поправьте роутинг. 
 Посмотрите доку https://habr.com/ru/post/351890/. И сделайте  роутинг по ресурсу как положено. + Необходим редирект на стартовую страницу после обновления ресурса. Пост запросы тоже не должны идти на стартовый урл.

2020-04-25 14:26 UTC, dimabalony commented
> В целом ок, но похоже что нашел какой то баг. Таска Done, а даты нет.
> ![image](https://user-images.githubusercontent.com/22429308/80281628-2f8c2c80-8715-11ea-86a8-54e829f13122.png) Надо бы поправить. Это одно.
> Второе, поправьте роутинг.
> Посмотрите доку https://habr.com/ru/post/351890/. И сделайте роутинг по ресурсу как положено. + Необходим редирект на стартовую страницу после обновления ресурса. Пост запросы тоже не должны идти на стартовый урл.

1. Я не добавлял функциональности, поэтому это не баг, а просто непредусмотрено)
2. Роутинг делал как знал, потому что работаю на клиентской части, поэтому спасибо за бюст практиз, сейчас что-нибудь поменяю)
3. Не понял когда должен быть редирект, имеется в виду после обновления конкретной модели? 
4. Здесь тоже не особо понял. Имеется в виду, что необходимо сделать домашнюю страницу, а кнопкой например "Список задач" и дальше уже там (/todoslist) реализовать круд, то есть отправлять запросы на (/todoslist)?

2020-04-25 15:33 UTC, DmitryGolubko requested changes
1. Ок, тогда логічнее было бы просто не показывать это поле
2. Роутинг переделайте
3. Про редиректы: Гляньте эти ссылокчи https://ilyabirman.ru/meanwhile/all/web-developers-golden-rule/ https://habr.com/ru/post/86258/
4. список задач можете оставить так, хотя если посмотрите бюст практиз, то увидите что роуты должны быть как то так:
GET /tasks - полуение списка задач
GET /tasks/new - страница добавления новой задачи, этот роут необязательный, если форма есть на странице со списком.
POST /tasks - добавление новой задачи, после нее редирект на GET /tasks
GET /tasks/id - просмотр конкретной задачи, может быть совмещено с /edit если форма для апдейта прямо на странице просмотра
PUT /tasks/id - обновление задачи
DELETE /tasks/id - удаление
GET /tasks/id/edit - открытие страницы для редактирования, тоже необязательный урл.
Новых страниц не добавляйте, а вот пути надо поправить

2020-04-26 11:07 UTC, dimabalony commented
> * Ок, тогда логічнее было бы просто не показывать это поле
> * Роутинг переделайте
> * Про редиректы: Гляньте эти ссылокчи https://ilyabirman.ru/meanwhile/all/web-developers-golden-rule/ https://habr.com/ru/post/86258/
> * список задач можете оставить так, хотя если посмотрите бюст практиз, то увидите что роуты должны быть как то так:
>   GET /tasks - полуение списка задач
>   GET /tasks/new - страница добавления новой задачи, этот роут необязательный, если форма есть на странице со списком.
>   POST /tasks - добавление новой задачи, после нее редирект на GET /tasks
>   GET /tasks/id - просмотр конкретной задачи, может быть совмещено с /edit если форма для апдейта прямо на странице просмотра
>   PUT /tasks/id - обновление задачи
>   DELETE /tasks/id - удаление
>   GET /tasks/id/edit - открытие страницы для редактирования, тоже необязательный урл.
>   Новых страниц не добавляйте, а вот пути надо поправить

2. Вы мне писали, проблема в PUT и DELETE. Я изначально так и хотел сделать и долго пытался понять почему не работает, но оказалось, что кнопка в html не может отправлять какой-либо запрос кроме POST и GET, поэтому и пришлось делать /delete и /update.
У меня например есть ещё один контроллер в проекте и там всё реализовано, как надо, то есть endpoint /todos на который отправляются get, post, put, delete итд. Но он просто json возвращает, а тут html.

> PUT /tasks/id - обновление задачи
> DELETE /tasks/id - удаление

3. Так у меня же есть редиректы? После добавления и удаления редирект на главную страницу и после обновления редирект на страницу, конкретной задачи.

2020-04-27 07:39 UTC, DmitryGolubko approved these changes
Да. вы правы, я забыл что html формами мжоно только отправлять GET и POST. Но из этой ситуации можно выкрутится адажксом для удаления, и пост запросом на /list/id для обновления, тогда было бы все правильно.
Редиректы есть, тоже все правильно здесь, я просто сразу не обратил внимание что данные обновляются.
В общем, тут немного мой косяк был, так что принято. Но во второй роутинг должен быть по канонам, там проблем уже быть не должно.

2020-04-27 11:38 UTC, merged